package com.floreantpos.model.base;

import com.floreantpos.model.InventoryVendor;
import com.floreantpos.model.Person;
import com.floreantpos.model.VendorPerson;

// Generated 27 Apr, 2015 7:50:23 PM by Hibernate Tools 3.4.0.CR1

/**
 * VendorPerson generated by hbm2java
 */
public class BaseVendorPerson implements java.io.Serializable {

	public static String PROP_ID = "id";
	public static String PROP_VENDOR = "vendor";
	public static String PROP_PERSON = "person";

	private Integer id;
	private InventoryVendor vendor;
	private Person person;
	private int hashCode = Integer.MIN_VALUE;

	public BaseVendorPerson() {
	}

	public BaseVendorPerson(InventoryVendor vendor, Person person) {
		this.vendor = vendor;
		this.person = person;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public InventoryVendor getVendor() {
		return this.vendor;
	}

	public void setVendor(InventoryVendor vendor) {
		this.vendor = vendor;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public boolean equals(Object obj) {
		if (null == obj)
			return false;
		if (!(obj instanceof VendorPerson))
			return false;
		else {
			VendorPerson vendPers = (VendorPerson) obj;
			return (this.getVendor().equals(vendPers.getVendor()) && this.getPerson().equals(vendPers.getPerson()));
		}
	}

	public int hashCode() {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId())
				return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}

	public int compareTo(Object obj) {
		if (obj.hashCode() > hashCode())
			return 1;
		else if (obj.hashCode() < hashCode())
			return -1;
		else
			return 0;
	}

	public String toString() {
		return super.toString();
	}

}
