package com.floreantpos.model.base;

// Generated 25 Apr, 2015 1:56:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.floreantpos.model.Company;
import com.floreantpos.model.InventoryTransaction;

/**
 * Company generated by hbm2java
 */
public class BaseCompany implements java.io.Serializable {

	@Override
	public String toString() {
		return name;
	}

	private Integer id;
	private String name;
	private String phone;
	private String email;
	private String address;
	private Set<BaseItemCompVendPack> itemCompVendPacks = new HashSet<BaseItemCompVendPack>(0);
	private Set<InventoryTransaction> inventoryTransactions = new HashSet<InventoryTransaction>(0);
	private int hashCode = Integer.MIN_VALUE;

	public BaseCompany() {
	}

	public BaseCompany(String name) {
		this.name = name;
	}

	public BaseCompany(String name, String phone, String email, String address, Set<BaseItemCompVendPack> itemCompVendPacks, Set<InventoryTransaction> inventoryTransactions) {
		this.name = name;
		this.phone = phone;
		this.email = email;
		this.address = address;
		this.itemCompVendPacks = itemCompVendPacks;
		this.inventoryTransactions = inventoryTransactions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Set<BaseItemCompVendPack> getItemCompVendPacks() {
		return this.itemCompVendPacks;
	}

	public void setItemCompVendPacks(Set<BaseItemCompVendPack> itemCompVendPacks) {
		this.itemCompVendPacks = itemCompVendPacks;
	}

	public Set<InventoryTransaction> getInventoryTransactions() {
		return this.inventoryTransactions;
	}

	public void setInventoryTransactions(Set<InventoryTransaction> inventoryTransactions) {
		this.inventoryTransactions = inventoryTransactions;
	}

	public boolean equals(Object obj) {
		if (null == obj)
			return false;
		if (!(obj instanceof Company))
			return false;
		else {
			Company company = (Company) obj;
			if (null == this.getId() || null == company.getId())
				return false;
			else
				return (this.getId().equals(company.getId()));
		}
	}

	public int hashCode() {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId())
				return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}

	public int compareTo(Object obj) {
		if (obj.hashCode() > hashCode())
			return 1;
		else if (obj.hashCode() < hashCode())
			return -1;
		else
			return 0;
	}

}
