package com.floreantpos.model.base;

// Generated 25 Apr, 2015 1:56:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.floreantpos.model.ExpenseTransaction;

/**
 * ExpenseHead generated by hbm2java
 */
public class BaseExpenseHead implements java.io.Serializable {

	private Integer id;
	private String name;
	private Boolean visible;
	private Set<ExpenseTransaction> expenseTransactions = new HashSet<ExpenseTransaction>(0);

	public BaseExpenseHead() {
	}

	public BaseExpenseHead(String name) {
		this.name = name;
	}

	public BaseExpenseHead(String name, Boolean visible, Set<ExpenseTransaction> expenseTransactions) {
		this.name = name;
		this.visible = visible;
		this.expenseTransactions = expenseTransactions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getVisible() {
		return this.visible;
	}

	public void setVisible(Boolean visible) {
		this.visible = visible;
	}

	public Set<ExpenseTransaction> getExpenseTransactions() {
		return this.expenseTransactions;
	}

	public void setExpenseTransactions(Set<ExpenseTransaction> expenseTransactions) {
		this.expenseTransactions = expenseTransactions;
	}

}
