package com.floreantpos.model.base;

// Generated 25 Apr, 2015 1:56:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.floreantpos.model.InventoryTransaction;
import com.floreantpos.model.PackSize;

/**
 * PackSize generated by hbm2java
 */
public class BasePackSize implements java.io.Serializable {

	public static String REF = "PackagingSize";
	public static String PROP_SIZE = "size";
	public static String PROP_ID = "id";
	public static String PROP_VISIBLE = "visible";

	private Integer id;
	private int size;
	private Boolean visible;
	private Set<InventoryTransaction> inventoryTransactions = new HashSet<InventoryTransaction>(0);
	private Set<BaseItemCompVendPack> itemCompVendPacks = new HashSet<BaseItemCompVendPack>(0);
	private int hashCode = Integer.MIN_VALUE;

	public BasePackSize() {
	}

	public BasePackSize(int size) {
		this.size = size;
		this.visible = true;
	}

	public BasePackSize(int size, Boolean visible, Set<InventoryTransaction> inventoryTransactions, Set<BaseItemCompVendPack> itemCompVendPacks) {
		this.size = size;
		this.visible = visible;
		this.inventoryTransactions = inventoryTransactions;
		this.itemCompVendPacks = itemCompVendPacks;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getSize() {
		return this.size;
	}

	public void setSize(int size) {
		this.size = size;
	}

	public Boolean getVisible() {
		return this.visible;
	}

	public void setVisible(Boolean visible) {
		this.visible = visible;
	}

	public Set<InventoryTransaction> getInventoryTransactions() {
		return this.inventoryTransactions;
	}

	public void setInventoryTransactions(Set<InventoryTransaction> inventoryTransactions) {
		this.inventoryTransactions = inventoryTransactions;
	}

	public Set<BaseItemCompVendPack> getItemCompVendPacks() {
		return this.itemCompVendPacks;
	}

	public void setItemCompVendPacks(Set<BaseItemCompVendPack> itemCompVendPacks) {
		this.itemCompVendPacks = itemCompVendPacks;
	}

	@Override
	public String toString() {
		return Integer.toString(size);
	}

	public boolean equals(Object obj) {
		if (null == obj)
			return false;
		if (!(obj instanceof PackSize))
			return false;
		else {
			PackSize packSize = (PackSize) obj;
			if (null == this.getId() || null == packSize.getId())
				return false;
			else
				return (this.getId().equals(packSize.getId()));
		}
	}

	public int hashCode() {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId())
				return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}

	public int compareTo(Object obj) {
		if (obj.hashCode() > hashCode())
			return 1;
		else if (obj.hashCode() < hashCode())
			return -1;
		else
			return 0;
	}

}
