package com.floreantpos.model.base;

// Generated 25 Apr, 2015 1:56:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.floreantpos.model.InventoryTransaction;

/**
 * Company generated by hbm2java
 */
public class BaseCompany implements java.io.Serializable {

	private Integer id;
	private BasePerson personByP2Id;
	private BasePerson personByP5Id;
	private BasePerson personByP4Id;
	private BasePerson personByP6Id;
	private BasePerson personByP1Id;
	private BasePerson personByP3Id;
	private String name;
	private String phone;
	private String email;
	private String address;
	private Set<BaseItemCompVendPack> itemCompVendPacks = new HashSet<BaseItemCompVendPack>(0);
	private Set<InventoryTransaction> inventoryTransactions = new HashSet<InventoryTransaction>(0);

	public BaseCompany() {
	}

	public BaseCompany(String name) {
		this.name = name;
	}

	public BaseCompany(BasePerson personByP2Id, BasePerson personByP5Id, BasePerson personByP4Id, BasePerson personByP6Id, BasePerson personByP1Id, BasePerson personByP3Id,
			String name, String phone, String email, String address, Set<BaseItemCompVendPack> itemCompVendPacks,
			Set<InventoryTransaction> inventoryTransactions) {
		this.personByP2Id = personByP2Id;
		this.personByP5Id = personByP5Id;
		this.personByP4Id = personByP4Id;
		this.personByP6Id = personByP6Id;
		this.personByP1Id = personByP1Id;
		this.personByP3Id = personByP3Id;
		this.name = name;
		this.phone = phone;
		this.email = email;
		this.address = address;
		this.itemCompVendPacks = itemCompVendPacks;
		this.inventoryTransactions = inventoryTransactions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public BasePerson getPersonByP2Id() {
		return this.personByP2Id;
	}

	public void setPersonByP2Id(BasePerson personByP2Id) {
		this.personByP2Id = personByP2Id;
	}

	public BasePerson getPersonByP5Id() {
		return this.personByP5Id;
	}

	public void setPersonByP5Id(BasePerson personByP5Id) {
		this.personByP5Id = personByP5Id;
	}

	public BasePerson getPersonByP4Id() {
		return this.personByP4Id;
	}

	public void setPersonByP4Id(BasePerson personByP4Id) {
		this.personByP4Id = personByP4Id;
	}

	public BasePerson getPersonByP6Id() {
		return this.personByP6Id;
	}

	public void setPersonByP6Id(BasePerson personByP6Id) {
		this.personByP6Id = personByP6Id;
	}

	public BasePerson getPersonByP1Id() {
		return this.personByP1Id;
	}

	public void setPersonByP1Id(BasePerson personByP1Id) {
		this.personByP1Id = personByP1Id;
	}

	public BasePerson getPersonByP3Id() {
		return this.personByP3Id;
	}

	public void setPersonByP3Id(BasePerson personByP3Id) {
		this.personByP3Id = personByP3Id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Set<BaseItemCompVendPack> getItemCompVendPacks() {
		return this.itemCompVendPacks;
	}

	public void setItemCompVendPacks(Set<BaseItemCompVendPack> itemCompVendPacks) {
		this.itemCompVendPacks = itemCompVendPacks;
	}

	public Set<InventoryTransaction> getInventoryTransactions() {
		return this.inventoryTransactions;
	}

	public void setInventoryTransactions(Set<InventoryTransaction> inventoryTransactions) {
		this.inventoryTransactions = inventoryTransactions;
	}

}
