package com.floreantpos.model.base;

// Generated 25 Apr, 2015 1:56:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.floreantpos.model.InventoryVendor;

/**
 * Person generated by hbm2java
 */
public class BasePerson implements java.io.Serializable {

	private Integer id;
	private String name;
	private String phone;
	private String email;
	private String designation;
	private String address;
	private Set<InventoryVendor> inventoryVendorsForP7Id = new HashSet<InventoryVendor>(0);
	private Set<InventoryVendor> inventoryVendorsForP6Id = new HashSet<InventoryVendor>(0);
	private Set<InventoryVendor> inventoryVendorsForP5Id = new HashSet<InventoryVendor>(0);
	private Set<BaseCompany> companiesForP1Id = new HashSet<BaseCompany>(0);
	private Set<InventoryVendor> inventoryVendorsForP4Id = new HashSet<InventoryVendor>(0);
	private Set<BaseCompany> companiesForP6Id = new HashSet<BaseCompany>(0);
	private Set<InventoryVendor> inventoryVendorsForP3Id = new HashSet<InventoryVendor>(0);
	private Set<InventoryVendor> inventoryVendorsForP2Id = new HashSet<InventoryVendor>(0);
	private Set<BaseCompany> companiesForP3Id = new HashSet<BaseCompany>(0);
	private Set<BaseCompany> companiesForP4Id = new HashSet<BaseCompany>(0);
	private Set<BaseCompany> companiesForP5Id = new HashSet<BaseCompany>(0);
	private Set<BaseCompany> companiesForP2Id = new HashSet<BaseCompany>(0);

	public BasePerson() {
	}

	public BasePerson(String name) {
		this.name = name;
	}

	public BasePerson(String name, String phone, String email, String designation, String address, Set<InventoryVendor> inventoryVendorsForP7Id,
			Set<InventoryVendor> inventoryVendorsForP6Id, Set<InventoryVendor> inventoryVendorsForP5Id, Set<BaseCompany> companiesForP1Id,
			Set<InventoryVendor> inventoryVendorsForP4Id, Set<BaseCompany> companiesForP6Id, Set<InventoryVendor> inventoryVendorsForP3Id,
			Set<InventoryVendor> inventoryVendorsForP2Id, Set<BaseCompany> companiesForP3Id, Set<BaseCompany> companiesForP4Id,
			Set<BaseCompany> companiesForP5Id, Set<BaseCompany> companiesForP2Id) {
		this.name = name;
		this.phone = phone;
		this.email = email;
		this.designation = designation;
		this.address = address;
		this.inventoryVendorsForP7Id = inventoryVendorsForP7Id;
		this.inventoryVendorsForP6Id = inventoryVendorsForP6Id;
		this.inventoryVendorsForP5Id = inventoryVendorsForP5Id;
		this.companiesForP1Id = companiesForP1Id;
		this.inventoryVendorsForP4Id = inventoryVendorsForP4Id;
		this.companiesForP6Id = companiesForP6Id;
		this.inventoryVendorsForP3Id = inventoryVendorsForP3Id;
		this.inventoryVendorsForP2Id = inventoryVendorsForP2Id;
		this.companiesForP3Id = companiesForP3Id;
		this.companiesForP4Id = companiesForP4Id;
		this.companiesForP5Id = companiesForP5Id;
		this.companiesForP2Id = companiesForP2Id;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Set<InventoryVendor> getInventoryVendorsForP7Id() {
		return this.inventoryVendorsForP7Id;
	}

	public void setInventoryVendorsForP7Id(Set<InventoryVendor> inventoryVendorsForP7Id) {
		this.inventoryVendorsForP7Id = inventoryVendorsForP7Id;
	}

	public Set<InventoryVendor> getInventoryVendorsForP6Id() {
		return this.inventoryVendorsForP6Id;
	}

	public void setInventoryVendorsForP6Id(Set<InventoryVendor> inventoryVendorsForP6Id) {
		this.inventoryVendorsForP6Id = inventoryVendorsForP6Id;
	}

	public Set<InventoryVendor> getInventoryVendorsForP5Id() {
		return this.inventoryVendorsForP5Id;
	}

	public void setInventoryVendorsForP5Id(Set<InventoryVendor> inventoryVendorsForP5Id) {
		this.inventoryVendorsForP5Id = inventoryVendorsForP5Id;
	}

	public Set<BaseCompany> getCompaniesForP1Id() {
		return this.companiesForP1Id;
	}

	public void setCompaniesForP1Id(Set<BaseCompany> companiesForP1Id) {
		this.companiesForP1Id = companiesForP1Id;
	}

	public Set<InventoryVendor> getInventoryVendorsForP4Id() {
		return this.inventoryVendorsForP4Id;
	}

	public void setInventoryVendorsForP4Id(Set<InventoryVendor> inventoryVendorsForP4Id) {
		this.inventoryVendorsForP4Id = inventoryVendorsForP4Id;
	}

	public Set<BaseCompany> getCompaniesForP6Id() {
		return this.companiesForP6Id;
	}

	public void setCompaniesForP6Id(Set<BaseCompany> companiesForP6Id) {
		this.companiesForP6Id = companiesForP6Id;
	}

	public Set<InventoryVendor> getInventoryVendorsForP3Id() {
		return this.inventoryVendorsForP3Id;
	}

	public void setInventoryVendorsForP3Id(Set<InventoryVendor> inventoryVendorsForP3Id) {
		this.inventoryVendorsForP3Id = inventoryVendorsForP3Id;
	}

	public Set<InventoryVendor> getInventoryVendorsForP2Id() {
		return this.inventoryVendorsForP2Id;
	}

	public void setInventoryVendorsForP2Id(Set<InventoryVendor> inventoryVendorsForP2Id) {
		this.inventoryVendorsForP2Id = inventoryVendorsForP2Id;
	}

	public Set<BaseCompany> getCompaniesForP3Id() {
		return this.companiesForP3Id;
	}

	public void setCompaniesForP3Id(Set<BaseCompany> companiesForP3Id) {
		this.companiesForP3Id = companiesForP3Id;
	}

	public Set<BaseCompany> getCompaniesForP4Id() {
		return this.companiesForP4Id;
	}

	public void setCompaniesForP4Id(Set<BaseCompany> companiesForP4Id) {
		this.companiesForP4Id = companiesForP4Id;
	}

	public Set<BaseCompany> getCompaniesForP5Id() {
		return this.companiesForP5Id;
	}

	public void setCompaniesForP5Id(Set<BaseCompany> companiesForP5Id) {
		this.companiesForP5Id = companiesForP5Id;
	}

	public Set<BaseCompany> getCompaniesForP2Id() {
		return this.companiesForP2Id;
	}

	public void setCompaniesForP2Id(Set<BaseCompany> companiesForP2Id) {
		this.companiesForP2Id = companiesForP2Id;
	}

}
