package com.floreantpos.model.base;

// Generated 25 Apr, 2015 1:56:53 PM by Hibernate Tools 3.4.0.CR1

import com.floreantpos.model.Person;

/**
 * Person generated by hbm2java
 */
public class BasePerson implements java.io.Serializable {

	private Integer id;
	private String name;
	private String ref;
	private String phone;
	private String email;
	private String designation;
	private String address;
	private int hashCode = Integer.MIN_VALUE;

	public BasePerson() {
	}

	public BasePerson(String name) {
		this.name = name;
	}

	public BasePerson(String name, String ref, String phone, String email, String designation, String address) {
		this.name = name;
		this.phone = phone;
		this.email = email;
		this.designation = designation;
		this.address = address;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRef() {
		return this.ref;
	}

	public void setRef(String ref) {
		this.ref = ref;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Override
	public String toString() {
		return name + "-" + ref;
	}

	public boolean equals(Object obj) {
		if (null == obj)
			return false;
		if (!(obj instanceof Person))
			return false;
		else {
			Person person = (Person) obj;
			if (null == this.getId() || null == person.getId())
				return false;
			else
				return (this.getId().equals(person.getId()));
		}
	}

	public int hashCode() {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId())
				return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}

	public int compareTo(Object obj) {
		if (obj.hashCode() > hashCode())
			return 1;
		else if (obj.hashCode() < hashCode())
			return -1;
		else
			return 0;
	}

}
