package com.floreantpos.model.base;

import com.floreantpos.model.InventoryItem;
import com.floreantpos.model.InventoryVendor;

// Generated 25 Apr, 2015 1:56:53 PM by Hibernate Tools 3.4.0.CR1

/**
 * ItemCompVendPack generated by hbm2java
 */
public class BaseItemCompVendPack implements java.io.Serializable {

	private Integer id;
	private BasePackSize packSize;
	private BaseCompany company;
	private InventoryVendor inventoryVendor;
	private InventoryItem inventoryItem;

	public BaseItemCompVendPack() {
	}

	public BaseItemCompVendPack(BasePackSize packSize, BaseCompany company, InventoryVendor inventoryVendor, InventoryItem inventoryItem) {
		this.packSize = packSize;
		this.company = company;
		this.inventoryVendor = inventoryVendor;
		this.inventoryItem = inventoryItem;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public BasePackSize getPackSize() {
		return this.packSize;
	}

	public void setPackSize(BasePackSize packSize) {
		this.packSize = packSize;
	}

	public BaseCompany getCompany() {
		return this.company;
	}

	public void setCompany(BaseCompany company) {
		this.company = company;
	}

	public InventoryVendor getInventoryVendor() {
		return this.inventoryVendor;
	}

	public void setInventoryVendor(InventoryVendor inventoryVendor) {
		this.inventoryVendor = inventoryVendor;
	}

	public InventoryItem getInventoryItem() {
		return this.inventoryItem;
	}

	public void setInventoryItem(InventoryItem inventoryItem) {
		this.inventoryItem = inventoryItem;
	}

}
