package com.floreantpos.model.base;

// Generated 25 Apr, 2015 1:56:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.floreantpos.model.ExpenseHead;
import com.floreantpos.model.ExpenseTransaction;

/**
 * ExpenseHead generated by hbm2java
 */
public class BaseExpenseHead implements java.io.Serializable {

	private Integer id;
	private String name;
	private Boolean visible;
	private Set<ExpenseTransaction> expenseTransactions = new HashSet<ExpenseTransaction>(0);
	private int hashCode = Integer.MIN_VALUE;

	public BaseExpenseHead() {
	}

	public BaseExpenseHead(String name) {
		this.name = name;
	}

	public BaseExpenseHead(String name, Boolean visible, Set<ExpenseTransaction> expenseTransactions) {
		this.name = name;
		this.visible = visible;
		this.expenseTransactions = expenseTransactions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getVisible() {
		return this.visible;
	}

	public void setVisible(Boolean visible) {
		this.visible = visible;
	}

	public Set<ExpenseTransaction> getExpenseTransactions() {
		return this.expenseTransactions;
	}

	public void setExpenseTransactions(Set<ExpenseTransaction> expenseTransactions) {
		this.expenseTransactions = expenseTransactions;
	}

	@Override
	public String toString() {
		return name;
	}

	public boolean equals(Object obj) {
		if (null == obj)
			return false;
		if (!(obj instanceof ExpenseHead))
			return false;
		else {
			ExpenseHead expHead = (ExpenseHead) obj;
			if (null == this.getId() || null == expHead.getId())
				return false;
			else
				return (this.getId().equals(expHead.getId()));
		}
	}

	public int hashCode() {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId())
				return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}

	public int compareTo(Object obj) {
		if (obj.hashCode() > hashCode())
			return 1;
		else if (obj.hashCode() < hashCode())
			return -1;
		else
			return 0;
	}

}
