package com.floreantpos.model;

import java.util.Set;

import com.floreantpos.model.base.BaseExpenseHead;

// Generated 25 Apr, 2015 1:56:53 PM by Hibernate Tools 3.4.0.CR1

/**
 * Company generated by hbm2java
 */
public class ExpenseHead extends BaseExpenseHead {

	public ExpenseHead() {
		super();
		// TODO Auto-generated constructor stub
	}

	public ExpenseHead(String name, Boolean visible, Set<ExpenseTransaction> expenseTransactions) {
		super(name, visible, expenseTransactions);
		// TODO Auto-generated constructor stub
	}

	public ExpenseHead(String name) {
		super(name);
		// TODO Auto-generated constructor stub
	}

}
