package com.floreantpos.model;

import java.util.Set;

import com.floreantpos.model.base.BaseItemCompVendPack;
import com.floreantpos.model.base.BasePackSize;

// Generated 25 Apr, 2015 1:56:53 PM by Hibernate Tools 3.4.0.CR1

/**
 * Company generated by hbm2java
 */
public class PackSize extends BasePackSize {

	public PackSize() {
		super();
		// TODO Auto-generated constructor stub
	}

	public PackSize(int size, Boolean visible, Set<InventoryTransaction> inventoryTransactions, Set<BaseItemCompVendPack> itemCompVendPacks) {
		super(size, visible, inventoryTransactions, itemCompVendPacks);
		// TODO Auto-generated constructor stub
	}

	public PackSize(int size) {
		super(size);
		// TODO Auto-generated constructor stub
	}

}
