package com.floreantpos.model;

import com.floreantpos.model.base.BasePerson;

// Generated 25 Apr, 2015 1:56:53 PM by Hibernate Tools 3.4.0.CR1

/**
 * Company generated by hbm2java
 */
public class Person extends BasePerson {

}
