package com.floreantpos.model;

import java.util.Set;

import com.floreantpos.model.base.BaseCompany;
import com.floreantpos.model.base.BasePerson;

// Generated 25 Apr, 2015 1:56:53 PM by Hibernate Tools 3.4.0.CR1

/**
 * Company generated by hbm2java
 */
public class Person extends BasePerson {

	public Person() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Person(String name, String phone, String email, String designation, String address, Set<InventoryVendor> inventoryVendorsForP7Id, Set<InventoryVendor> inventoryVendorsForP6Id,
			Set<InventoryVendor> inventoryVendorsForP5Id, Set<BaseCompany> companiesForP1Id, Set<InventoryVendor> inventoryVendorsForP4Id, Set<BaseCompany> companiesForP6Id,
			Set<InventoryVendor> inventoryVendorsForP3Id, Set<InventoryVendor> inventoryVendorsForP2Id, Set<BaseCompany> companiesForP3Id, Set<BaseCompany> companiesForP4Id,
			Set<BaseCompany> companiesForP5Id, Set<BaseCompany> companiesForP2Id) {
		super(name, phone, email, designation, address, inventoryVendorsForP7Id, inventoryVendorsForP6Id, inventoryVendorsForP5Id, companiesForP1Id, inventoryVendorsForP4Id, companiesForP6Id,
				inventoryVendorsForP3Id, inventoryVendorsForP2Id, companiesForP3Id, companiesForP4Id, companiesForP5Id, companiesForP2Id);
		// TODO Auto-generated constructor stub
	}

	public Person(String name) {
		super(name);
		// TODO Auto-generated constructor stub
	}

}
